# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-18 12:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_post_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content',
            field=models.TextField(default='content'),
        ),
    ]
