# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-18 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='imagae3',
            field=models.ImageField(default='static/blog/images/blank.jpg', upload_to=''),
        ),
        migrations.AddField(
            model_name='post',
            name='image2',
            field=models.ImageField(default='static/blog/images/blank.jpg', upload_to=''),
        ),
    ]
