# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-18 14:44
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20180218_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='test',
            field=tinymce.models.HTMLField(default='Content'),
        ),
    ]
