# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-18 17:55
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_remove_post_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='test',
            field=tinymce.models.HTMLField(default=''),
        ),
    ]
