# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-20 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20180220_1922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image3',
        ),
        migrations.AddField(
            model_name='post',
            name='references',
            field=models.TextField(default=''),
        ),
    ]
